### ISSUE TITLE
How to run BERT-CRF baseline?

### ISSUE THREAD

**Issue by Elanmarkowitz** [xuuuluuu/SynLSTM-for-NER#3]
Hi, how do I run the BERT-CRF baseline? I only see `["none", "dggcn", "dglstm"]` as options in the parser.

Thanks!

**Comment by xuuuluuu** [comment]
Hi, thanks for following our work. 
The current setup can support BERT-CRF but requires some simple modifications. I will arrange my time to do the modification. Meanwhile, I also used the repo below to check the BERT-CRF performance. https://github.com/allanj/pytorch_neural_crf
