### ISSUE TITLE
您好，图神经网络的邻接矩阵为什么用inst.input.heads（head_to_adj），用inst.input.words可以构建邻接矩阵吗

### ISSUE THREAD

**Issue by hjg-ok** [xuuuluuu/SynLSTM-for-NER#4]

**Comment by allanj** [comment]
heads 里面包含每个word 的parent 信息。 input.words 里面没有dependency 信息，只有每个位置的单词

**Comment by hjg-ok** [comment]
> heads 里面包含每个word 的parent 信息。 input.words 里面没有dependency 信息，只有每个位置的单词

感谢回答。如果用其他数据集，可以不用head，而是根据文本字符用依存树构建邻接矩阵吗？

**Comment by allanj** [comment]
可以的。head 组合起来就是就是依存树， 所以其实都是用依存树
