### ISSUE TITLE
context embeddings error

### ISSUE THREAD

**Issue by karimmahalian** [xuuuluuu/SynLSTM-for-NER#5]
Hi,

Thank u for sharing ur code with us. I tried to run this command 

bert-serving-start -pooling_layer -7 -model_dir cased_L-24_H-1024_A-16 -max_seq_len=NONE -cased_tokenization -num_worker=8 -port=8888 -pooling_strategy=NONE -cpu -show_tokens_to_client

but I got this error

self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: cannot unpack non-iterable NoneType object

Any ideas plz? thank u

**Comment by xuuuluuu** [comment]
Hi, this is the error from bert-as-service. May I check if you have successfully installed the bert-as-service package? Do you have more details of the error?

**Comment by karimmahalian** [comment]
Hi,

First thank u for ur quick reply. Yes, the bert-as-service package was installed successfully.

Here are more details about the error

![Screen Shot 2022-07-27 at 6 49 00 AM](https://user-images.githubusercontent.com/90440701/181170993-def28602-072e-4da5-8a5b-258dd0898b50.png)
 

Many thanks in advance!

**Comment by allanj** [comment]
Hi @karimmahalian , I happen to reproduce your error. I think that's caused by the TensorFlow version issue. 
<img width="931" alt="image" src="https://user-images.githubusercontent.com/3351187/181172869-fd55dfec-0773-4084-bab3-841e56a1cb65.png">


I tried installing `tensorflow == 1.13.1`, then running the command you show should work:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/3351187/181172979-1ee8f294-44ab-4327-b99b-83fff0e57ea6.png">

**Comment by karimmahalian** [comment]
Hi 

I think I am confused. Do we have to download cased_L-24_H-1024_A-16
here is an error I  ve missed

tensorflow.python.framework.errors_impl.NotFoundError: cased_L-24_H-1024_A-16/bert_config.json; No such file or directory

Thanks

**Comment by allanj** [comment]
Yes, it seems you have to 

`wget https://storage.googleapis.com/bert_models/2018_10_18/cased_L-24_H-1024_A-16.zip`

I downloaded from the google BERT repo (https://github.com/google-research/bert#pre-trained-models)

**Comment by karimmahalian** [comment]
Yesss, it works now. However, it tooks a lot of time to be executed. I ve changed Bert large by Bert basic but still the same issue. Could u plz tell me how to run it on GPU instead of CPU?

![Screen Shot 2022-07-28 at 6 42 59 AM](https://user-images.githubusercontent.com/90440701/181429462-2a2bd0f4-157b-4d8f-804b-22b480ebf444.png)

I really appreciate the time u offer to help run the code. Thank u!

**Comment by allanj** [comment]
I'm not the main maintainer, but looking at the document in the "bert-as-service" (https://github.com/llSourcell/bert-as-service)

It seems the default is GPU?
<img width="863" alt="image" src="https://user-images.githubusercontent.com/3351187/181436679-8f1b81f6-1afa-4737-aa43-70c9f6b72497.png">


May be you can try specify the `device_map=[0]`

**Comment by allanj** [comment]
Oh, I saw your command here:

```bash
bert-serving-start -pooling_layer -7 -model_dir cased_L-24_H-1024_A-16 -max_seq_len=NONE -cased_tokenization -num_worker=8 -port=8888 -pooling_strategy=NONE -cpu -show_tokens_to_client
```

You explicitly specify `cpu`, please remove that argument and it will run on GPU.

**Comment by karimmahalian** [comment]
Yes, u re right I didn t pay attention to it. Thank u
